name: linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -c Release
